#!/bin/bash

files=$( fd . ~/.dotfiles ~/dev ~/notes --type f --hidden --follow --exclude .git && fd . $HOME -d 1 --type f --hidden --exclude .git )
# Find files using fd (better than find), filter with fzf for interactive selection
selected_files=$( echo "$files" | fzf --layout=reverse --preview-window up --preview "bat -n --color=always {}" --bind ctrl-u:preview-up,ctrl-d:preview-down )

# If no file is selected, exit gracefully
if [ -z "$selected_files" ]; then
    exit 0
else
    # Extract directory path from the selected file
    dir=$(dirname "$selected_files")
    
    # Change directory to the path of the selected file and open it in nvim
    cd "$dir" && nvim "$selected_files"
fi


