#!/usr/bin/env bash

RG_PREFIX="rga --files-with-matches --hidden"
DIR_LIST="~/notes ~/dev"
local file
file="$(
    FZF_DEFAULT_COMMAND="$RG_PREFIX '$1' $DIR_LIST" \
        fzf --sort --preview="[[ ! -z {} ]] && rga --pretty --context 5 {q} {}" \
            --phony -q "$1" \
            --bind "change:reload:$RG_PREFIX {q}  $DIR_LIST" \
            --bind ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down \
            --layout=reverse \
            --preview-window="wrap:up"
)" &&
echo "opening $file" &&
# open "$file"
nvim "$file"

