#!/bin/bash

dir=$( fd . ~/.dotfiles ~/dev ~/notes --type d --hidden --follow --exclude .git && fd . $HOME -d 1 --type d --hidden --exclude .git )
# Find files using fd (better than find), filter with fzf for interactive selection
selected_dir=$( echo "$dir" | fzf --layout=reverse --preview 'tree -C -L 5 {}')
if [ -d "$selected_dir" ]; then
    cd "$selected_dir" && echo "hello" 
else
    exit 0
fi

